global using MediatR;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json;
global using System.Diagnostics;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.Configuration;
global using System.Text;
global using FluentValidation; 
global using System.Text.Json;
