global using AutoMapper;
global using FluentValidation;
global using MaineXpert.EquipmentService.Application.Mediator.Queries;
global using MainteXpert.Common.Models.Base;
global using MainteXpert.Common.Models.Equipment;
global using MainteXpert.EquipmentService.Application.Mapper;
global using MainteXpert.EquipmentService.Application.Mediator.Commands;
global using MainteXpert.EquipmentService.Application.Mediator.Queries;
global using MainteXpert.MaintenanceSchedule.Application.Models;
global using MainteXpert.Middleware.Behaviors;
global using MainteXpert.Repository.Collections.Equipment;
global using MainteXpert.Repository.Interface;
global using MediatR;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using MongoDB.Driver;
global using Newtonsoft.Json;
global using Serilog;
global using System.Diagnostics;
global using System.Reflection;
global using EquipmentModel = MainteXpert.Common.Models.Equipment.EquipmentModel;

